name: Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: liauser
          POSTGRES_PASSWORD: liapassword
          POSTGRES_DB: liadb
        options: >-
          --health-cmd "pg_isready -U liauser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://liauser:liapassword@postgres:5432/liadb

    steps:
      - uses: actions/checkout@v3

      - name: Install PostgreSQL Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h postgres -p 5432 -U liauser; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
        shell: bash

      - name: Build
        run: |
          cd lia-src
          cargo build

      - name: Run tests
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          cd lia-src
          cargo test
